### ISSUE TITLE
Cannot invoke initializer for type 'UInt' with an argument list of type '(objc_AssociationPolicy)'

### ISSUE THREAD

**Issue by sekouperry** [Yalantis/Side-Menu.iOS#20]
In MenuSegue.swift
![screen shot 2015-09-18 at 4 08 56 pm](https://cloud.githubusercontent.com/assets/3640832/9969916/a0e2b094-5e1f-11e5-9825-cf5190222188.png)

func animationControllerForDismissedController(dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        dispatch_async(dispatch_get_main_queue()) {
            objc_setAssociatedObject(dismissed, &key, nil, UInt(objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC))
        }

**Comment by iSame7** [comment]
Hi @sekouperry I just fixed it by changing:
objc_setAssociatedObject(dismissed, &key, nil, UInt(objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC))

To: 
objc_setAssociatedObject(dismissed, &key, nil, objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)

OR: 
objc_setAssociatedObject(dismissed, &key, nil, .OBJC_ASSOCIATION_RETAIN)

Because objc_setAssociatedObject has also been updated to take a objc_AssociationPolicy argument instead of UInt.

**Comment by sekouperry** [comment]
Thanks

Sekou Perry

**Comment by EgorSobko** [comment]
Hi all, we've implemented this solution in a new version, thanks.

**Comment by Easyzhan** [comment]
that's help for me thx
